version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: IdentityModel
    versions:
    - 5.0.1
    - 5.1.0
  - dependency-name: IdentityServer4.Storage
    versions:
    - 4.1.2
  - dependency-name: IdentityServer4
    versions:
    - 4.1.2
  - dependency-name: Moq
    versions:
    - 4.16.1
